default:
  valueFiles:
  - values-k3d.yaml

applications:

  - name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "-10"

  - name: crossplane
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: external-secrets
    annotations:
      argocd.argoproj.io/sync-wave: "-8"

  - name: k8s-monitoring
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-8"
    syncOptions:
      - ServerSideApply=true

  - name: vault
    annotations:
      argocd.argoproj.io/sync-wave: "-7"

  - name: keycloak
    annotations:
      argocd.argoproj.io/sync-wave: "-5"

  - name: loki
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-1"
    helmOptions:
      skipCrds: true
    syncOptions:
      - ServerSideApply=true
      
  - name: grafana
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
    syncOptions:
      - ServerSideApply=true

  - name: mimir
    syncOptions:
      - ServerSideApply=true

  - name: tempo

   


