default:
  valueFiles:
  - values-k3d.yaml

applications:

  - name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "-10"

  - name: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: kube-prometheus-stack
    destinationNamespaceOverwrite: monitoring
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-6"
    syncOptions:
      - ServerSideApply=true

  - name: crossplane
    annotations:
      argocd.argoproj.io/sync-wave: "-8"

#  - name: loki
#    destinationNamespaceOverwrite: monitoring
#    annotations:
#      argocd.argoproj.io/compare-options: ServerSideDiff=true
#    helmOptions:
#      skipCrds: true
#    syncOptions:
#      - ServerSideApply=true

#  - name: promtail
#    destinationNamespaceOverwrite: monitoring
    
#  - name: tempo
#    destinationNamespaceOverwrite: monitoring

#  - name: falco
#    annotations:
#      argocd.argoproj.io/compare-options: ServerSideDiff=true
#    helmOptions:
#      skipCrds: true
#    syncOptions:
#      - ServerSideApply=true

  - name: external-secrets
    annotations:
      argocd.argoproj.io/sync-wave: "-8"

  - name: keycloak
    annotations:
      argocd.argoproj.io/sync-wave: "1"

#  - name: kargo

#  - name: komoplane

#  - name: kubecost

#  - name: team-onboarding
#    destinationNamespaceOverwrite: argocd

#  - name: argo-rollouts
      
#  - name: kyverno
#    syncOptions:
#      - ServerSideApply=true
#      
#  - name: backstage
#    annotations:
#      argocd.argoproj.io/sync-wave: "10"

  - name: vault
    annotations:
      argocd.argoproj.io/sync-wave: "-7"

  - name: velero
    annotations:
      argocd.argoproj.io/sync-wave: "5"
#  - name: velero-ui

  - name: minio
    annotations:
      argocd.argoproj.io/sync-wave: "-6"
