default:
  valueFiles:
  - values-kubrix-default.yaml
  - values-cluster-kind.yaml
  - values-customer.yaml

applications:
  - name: ingress-nginx
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: crossplane
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: external-secrets
    annotations:
      argocd.argoproj.io/sync-wave: "-9"
    syncOptions:
      - ServerSideApply=true

  - name: k8s-monitoring
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-9"
    syncOptions:
      - ServerSideApply=true

  - name: vault
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: cnpg
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-9"
    syncOptions:
      - ServerSideApply=true
      
  - name: keycloak
    annotations:
      argocd.argoproj.io/sync-wave: "-5"

  - name: testkube
    annotations:
      argocd.argoproj.io/sync-wave: "-5"

  - name: kargo
    annotations:
      argocd.argoproj.io/sync-wave: "-5"

  - name: backstage
    annotations:
      argocd.argoproj.io/sync-wave: "10"

  - name: team-onboarding
    destinationNamespaceOverwrite: argocd
    namespaceResourceTracking: false
    annotations:
      argocd.argoproj.io/sync-wave: "15"
