default:
  valueFiles:
  - values-kubrix-default.yaml
  - values-cluster-kind.yaml

applications:

  - name: traefik
    annotations:
      argocd.argoproj.io/sync-wave: "-11"

  - name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "-10"

  - name: crossplane
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: prometheus-operator-crds
    annotations:
      argocd.argoproj.io/sync-wave: "-9"
    syncOptions:
      - ServerSideApply=true

  - name: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-9"
    syncOptions:
      - ServerSideApply=true

  - name: external-secrets
    annotations:
      argocd.argoproj.io/sync-wave: "-8"
    syncOptions:
      - ServerSideApply=true

  - name: prometheus-blackbox-exporter
    annotations:
      argocd.argoproj.io/sync-wave: "-8"

  - name: k8s-monitoring
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-8"
    syncOptions:
      - ServerSideApply=true

  - name: vault
    annotations:
      argocd.argoproj.io/sync-wave: "-7"

  - name: cnpg
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-6"
    syncOptions:
      - ServerSideApply=true
      
  - name: keycloak
    annotations:
      argocd.argoproj.io/sync-wave: "-5"

  - name: loki
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-1"
    helmOptions:
      skipCrds: true
    syncOptions:
      - ServerSideApply=true
      
  - name: grafana
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
    syncOptions:
      - ServerSideApply=true

  - name: mimir

  - name: tempo

  - name: testkube

   


