default:
  valueFiles:
  - values-k3d.yaml

applications:

  - name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "-10"

  - name: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: external-secrets
    annotations:
      argocd.argoproj.io/sync-wave: "-8"

  - name: crossplane
    annotations:
      argocd.argoproj.io/sync-wave: "-7"

  - name: k8s-monitoring
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-7"
    syncOptions:
      - ServerSideApply=true

  - name: keycloak
    annotations:
      argocd.argoproj.io/sync-wave: "-6"

  - name: vault
    annotations:
      argocd.argoproj.io/sync-wave: "-5"

  - name: kargo

  - name: team-onboarding
    destinationNamespaceOverwrite: argocd
    namespaceResourceTracking: false

  - name: argo-rollouts

  - name: backstage
    annotations:
      argocd.argoproj.io/sync-wave: "10"
      



