default:
  valueFiles:
  - values-kubrix-default.yaml
  - values-cluster-kind.yaml

applications:

  - name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "-3"

  - name: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-2"

  - name: k8s-monitoring
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-1"
    syncOptions:
      - ServerSideApply=true
  
  - name: crossplane
    annotations:
      argocd.argoproj.io/sync-wave: "-1"

  - name: grafana
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
    syncOptions:
      - ServerSideApply=true

  - name: mimir

  - name: loki
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
    helmOptions:
      skipCrds: true
    syncOptions:
      - ServerSideApply=true

  - name: tempo

  - name: falco
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
    helmOptions:
      skipCrds: true
    syncOptions:
      - ServerSideApply=true

  - name: external-secrets
    syncOptions:
      - ServerSideApply=true

  - name: keycloak

  - name: kargo

  - name: kubecost

  - name: argo-rollouts
    ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
      - /spec/preserveUnknownFields
      
  - name: kyverno
    syncOptions:
      - ServerSideApply=true
      
  - name: backstage
    annotations:
      argocd.argoproj.io/sync-wave: "10"

  - name: team-onboarding
    destinationNamespaceOverwrite: argocd
    namespaceResourceTracking: false
    annotations:
      argocd.argoproj.io/sync-wave: "15"
