default:
  valueFiles:
  - values-kubrix-default.yaml
  - values-kind.yaml

applications:

  - name: cert-manager
    annotations:
      argocd.argoproj.io/sync-wave: "-10"

  - name: crossplane
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: argocd
    annotations:
      argocd.argoproj.io/sync-wave: "-9"

  - name: external-secrets
    annotations:
      argocd.argoproj.io/sync-wave: "-8"
    syncOptions:
      - ServerSideApply=true

  - name: k8s-monitoring
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-8"
    syncOptions:
      - ServerSideApply=true

#  - name: cnpg
#    annotations:
#      argocd.argoproj.io/compare-options: ServerSideDiff=true
#      argocd.argoproj.io/sync-wave: "-6"
#    syncOptions:
#      - ServerSideApply=true
      
  - name: vault
    annotations:
      argocd.argoproj.io/sync-wave: "-7"

  - name: cnpg
    annotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
      argocd.argoproj.io/sync-wave: "-6"
    syncOptions:
      - ServerSideApply=true
      
  - name: keycloak
    annotations:
      argocd.argoproj.io/sync-wave: "-5"

  - name: backstage
    annotations:
      argocd.argoproj.io/sync-wave: "10"
