minio:
  enabled: true
  replicas: 1
  mode: standalone
  persistence:
    size: 5Gi
  resources:
    requests:
      memory: 2Gi
  buckets:
    - name: velero
      policy: public
      purge: false
    - name: kubecost
      policy: public
      purge: false
  metrics:
    serviceMonitor:
      enabled: true
      includeNode: true
  existingSecret: minio-admin-secret
  users:
    - accessKey: minio
      existingSecret: minio-admin-secret
      existingSecretKey: secretKey
      policy: consoleAdmin
  tls:
    enabled: true
    certSecret: "minio-server-tls"
    publicCrt: tls.crt
    privateKey: tls.key
  consoleIngress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/ttl: "60"
      cert-manager.io/cluster-issuer: default-issuer
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    path: /
    hosts: []
    tls: []
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/ttl: "60"
      cert-manager.io/cluster-issuer: default-issuer
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    path: /
    hosts: []
    tls: []