{{ if .Values.kyvernoPolicies.createKubevirtRolebinding.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-kubevirt-rolebinding
  annotations:
    policies.kyverno.io/title: Add RoleBinding
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: Namespace, RoleBinding
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      kubevirt template datavolume clone reuqires rolebinding for sa
spec:
  rules:
    - name: generate-kubevirt-rolebinding
      skipBackgroundRequests: true
      match:
        any:
        - resources:
            kinds:
            - Namespace
# disable
#            operations:
#            - CREATE
            selector:
              matchLabels:
                kubrix.io/kyverno: kubevirt-rolebinding
      generate:
        synchronize: true
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: kubevirt-rolebinding-{{`{{request.object.metadata.name}}`}}
        namespace: kubevirt
        data:
          subjects:
            - kind: ServiceAccount
              name: default
              namespace: "{{`{{request.object.metadata.name}}`}}"
          roleRef:
            kind: ClusterRole
            name: kubevirt-datavolume-permission
            apiGroup: rbac.authorization.k8s.io
{{- end }}

