kubevirt:
  version: v1.5.0
cdi:
  version: v1.62.0
datasources:
  enabled: true
  sources:
    - name: ubuntu-jammy-server
      url: http://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
      storage: 3G
      # description for backstage Software Catalog
      description: ubuntu 22.02 Base Image
    - name: fedora-cloud-base
      url: https://download.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
      storage: 10G
      description: fedora cloud 43 Base Image
