apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: kind-portal-playwright
  labels:
    type: kind-portal
spec:
  content:
    git:
      uri: {{ .Values.default.repoURL }}
      revision: {{ .Values.default.targetRevision }}
      paths:
      - e2e-tests/playwright
      usernameFrom:
        secretKeyRef:
          name: git-credentials
          key: username
      tokenFrom:
        secretKeyRef:
          name: git-credentials
          key: token
  container:
    image: mcr.microsoft.com/playwright:v1.56.1
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
    workingDir: /data/repo/e2e-tests/playwright
  job:
    activeDeadlineSeconds:  600
  steps:
  - name: Install dependencies
    shell: "npm ci"
  - name: Run tests
    run:
      shell: |
        mkdir /data/artifacts
        npx playwright test portal/ --project=chromium --reporter=list,junit,html --trace on
      env:
      - name: PLAYWRIGHT_JUNIT_OUTPUT_NAME
        value: "/data/artifacts/junit-report.xml"
      - name: PLAYWRIGHT_HTML_REPORT
        value: /data/artifacts/playwright-report
    steps:
    - name: Save artifacts
      condition: always
      artifacts:
        workingDir: /data/artifacts/
        paths:
        - '**/*'
