apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: kind-delivery-playwright
  labels:
    type: kind-delivery
spec:
  content:
    git:
      uri: {{ .Values.default.repoURL }}
      revision: {{ .Values.default.targetRevision }}
      paths:
      - e2e-tests/playwright
      usernameFrom:
        secretKeyRef:
          name: git-credentials
          key: username
      tokenFrom:
        secretKeyRef:
          name: git-credentials
          key: token
  container:
    image: mcr.microsoft.com/playwright:v1.58.0
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
    workingDir: /data/repo/e2e-tests/playwright
  job:
    activeDeadlineSeconds:  600
  steps:
  - name: Install dependencies
    shell: "npm ci"
  - name: Run tests
    run:
      shell: |
        npx playwright test --project=argocd-tests --project=kargo-tests --project=vault-tests --project=keycloak-tests --reporter=list,junit,html --trace on
      env:
      - name: PLAYWRIGHT_JUNIT_OUTPUT_NAME
        value: "/data/repo/e2e-tests/playwright/data/artifacts/junit-report.xml"
      - name: PLAYWRIGHT_HTML_REPORT
        value: "/data/repo/e2e-tests/playwright/data/artifacts/playwright-report"
    steps:
    - name: Save artifacts
      condition: always
      artifacts:
        workingDir: /data/repo/e2e-tests/playwright/data/artifacts/
        paths:
        - '**/*'
