openbao:
  server:
    ingress:
      hosts:
        - host: openbao.demo.kubrix.cloud
          paths: []
      tls:
        - secretName: openbao-server-tls
          hosts:
            - openbao.demo.kubrix.cloud
