k8s-monitoring:

  cluster:
    name: kubrix
  destinations:
    - name: metricsService
      type: prometheus
      url: http://sx-mimir-gateway.mimir.svc/api/v1/push
      tenantId: ''
    - name: logsService
      type: loki
      url: http://sx-loki-gateway.loki.svc/loki/api/v1/push
      tenantId: ''
  clusterMetrics:
    enabled: true
    opencost:
      enabled: false
    windows-exporter:
      enabled: false
      deploy: false
    kepler:
      enabled: false
    kubeDNS:
      enabled: true
      jobLabel: integrations/coredns
    kubelet:
      metricsTuning:
        includeMetrics:
          - kubelet_volume_stats_used_bytes
          - kubelet_evictions
    cadvisor:
      metricsTuning:
        includeMetrics:
          - machine_cpu_cores
          - container_oom_events_total
          - container_cpu_cfs_throttled_seconds_total
    apiServer:
      enabled: true
      metricsTuning:
        includeMetrics:
          - apiserver_requested_deprecated_apis
          - apiserver_request_total
          - apiserver_request_duration_seconds_sum
          - apiserver_request_duration_seconds_count
          - apiserver_request_sli_duration_seconds_count
          - apiserver_request_sli_duration_seconds_bucket
          - workqueue_depth
          - process_cpu_seconds_total
          - process_resident_memory_bytes
          - apiserver_requested_deprecated_apis
    kube-state-metrics:
      metricsTuning:
        includeMetrics:
          - kube_namespace_created
          - kube_namespace_labels
          - kube_pod_container_status_running
          - kube_pod_container_status_ready
          - kube_pod_container_status_waiting
          - kube_pod_container_status_terminated
          - kube_service_info
          - kube_endpoint_info
          - kube_ingress_info
          - kube_deployment_labels
          - kube_statefulset_labels
          - kube_daemonset_labels
          - kube_persistentvolumeclaim_info
          - kube_hpa_labels
          - kube_configmap_info
          - kube_secret_info
          - kube_networkpolicy_labels
          - kube_node_info
          - kube_pod_status_qos_class
          - kube_pod_container_status_last_terminated_exitcode
          - kube_poddisruptionbudget_status_desired_healthy
          - kube_poddisruptionbudget_status_current_healthy
    node-exporter:
      metricsTuning:
        includeMetrics:
          - node_uname_info
          - node_time_seconds
          - node_boot_time_seconds
          - node_load1
          - node_load5
          - node_load15
          - node_context_switches_total
          - node_intr_total
          - node_filefd_maximum
          - node_filefd_allocated
          - node_timex_estimated_error_seconds
          - node_timex_maxerror_seconds
          - node_network_receive_errs_total
          - node_network_transmit_errs_total
          - node_network_receive_packets_total
          - node_network_transmit_packets_total
          - node_netstat_Tcp_CurrEstab
          - node_nf_conntrack_entries
          - node_nf_conntrack_entries_limit
          - node_disk_read_bytes_total
          - node_disk_written_bytes_total
          - node_disk_reads_completed_total
          - node_disk_writes_completed_total
          - node_disk_io_now
    kubeControllerManager:
      enabled: true
    kubeProxy:
      enabled: true
    kubeScheduler:
      enabled: true
  alloy-metrics:
    logging:
      level: info
    enabled: true
    extraConfig: |
      mimir.rules.kubernetes "rules" {
        address = "http://sx-mimir-gateway.mimir.svc"
        tenant_id = "anonymous"

        rule_namespace_selector {
          match_expression {
              key      = "kubernetes.io/metadata.name"
              operator = "In"
              values   = ["mimir", "loki"]
            }
        }
        rule_selector {
            match_labels = {}
        }
      }

  clusterEvents:
    enabled: true
  alloy-singleton:
    enabled: true
  podLogs:
    enabled: true
    labelsToKeep:
      - app.kubernetes.io/name
      - container
      - instance
      - job
      - level
      - namespace
      - service.name
      - service.namespace
      - deployment.environment
      - deployment.environment.name
      - k8s.namespace.name
      - k8s.deployment.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - stream
      
  alloy-logs:
    enabled: true
  annotationAutodiscovery:
    enabled: true
  prometheusOperatorObjects:
    enabled: true
    crds:
      deploy: true
  integrations:
    alloy:
      instances:
        - name: alloy
          labelSelectors:
            app.kubernetes.io/name:
              - alloy-metrics
              - alloy-singleton
              - alloy-logs
          metrics:
            tuning:
              useDefaultAllowList: false
              includeMetrics:
                - alloy_build_info
