{{- if .Values.eso.providerUrl }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.eso.backendName }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"

spec:
  provider:
    vault:
      server: "{{ .Values.eso.providerUrl }}"
      path: "{{ .Values.eso.secretStore }}"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "openbao-init"
          key: "root_token"
          namespace: openbao
{{ end }}
