{{- if .Values.letsEncrypStagingClusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  {{- if .Values.letsEncrypStagingClusterIssuer.default }}
  name: default-issuer
  {{- else }}
  name: letsencrypt-staging
  {{- end }}
spec:
  acme:
    email: support@suxess-it.com
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-staging
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    solvers:
{{ toYaml .Values.solvers | indent 6 }}
{{ end }}
