apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.application_id}}
  description: ${{values.description}}
  labels:
    environments: ${{values.environments}}
spec:
  owner: ${{values.owner}}
