# applies to podtato-head-entry deployment only
ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: default-issuer
    external-dns.alpha.kubernetes.io/ttl: "60"
  hosts:
    - host: ${{values.team}}-${{values.application_id}}-prod.${{values.defaultDomainName}}
      paths:
        - path: /
          pathType: ImplementationSpecific
