cert:
  enabled: true

deployment:
  version: 1.3.3
  tls: 
    name: kubevirt-manager-server-tls
  ingress:
    host: kubevirt-manager-metalstack.platform-engineer.cloud
  service:
    name: kubevirt-manager
    port: 8080
