kyverno:
  backgroundController:
    resources:
      limits:
        memory: 1Gi
  reportsController:
    resources:
      limits:
        memory: 1Gi

  # workaround for argocd outofsync because of empty labels
  kyverno-api:
    labels:
      app.kubernetes.io/managed-by: helm
    annotations:
      foo: bar
