apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kube-prometheus-stack
  title: kube-prometheus-stack
  description: kube-prometheus-stack access over Grafana Dasboard
  links: 
    - url: https://grafana-127-0-0-1.nip.io
      title: Grafana Instance for sx-cnp-oss
      icon: web
    - url: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
      title: Official Documentation
      icon: web
spec:
  type: observability
  lifecycle: production
  owner: sx-cnp-oss
  system: sx-cnp-oss