apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: policy-admin
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: openbao-crossplane-providerconfig
  forProvider:
    audience: openbao
    backend: kubernetes
    boundServiceAccountNames:
    - default
    boundServiceAccountNamespaces:
    - vopenbaot
    roleName: policy-admin
    tokenPolicies:
    - kubrix-openbao
    tokenTtl: 60