apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  name: oidc
spec:
  forProvider:
    type: oidc
    path: oidc
---
apiVersion: jwt.vault.upbound.io/v1alpha1
kind: AuthBackend
metadata:
  name: oidc-backend
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  providerConfigRef:
    name: vault-crossplane-providerconfig
  forProvider:
    oidcDiscoveryUrl: https://keycloak-127-0-0-1.nip.io/realms/sx-cnp-oss
    oidcClientId: vault
    defaultRole: default
    oidcClientSecretSecretRef:
      name: sx-vault-demosecret
      key: demosecret
      namespace: vault
    type: oidc
    path: oidc
# tune not working?
apiVersion: jwt.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: oidc-backend-role
spec:
  providerConfigRef:
    name: vault-crossplane-providerconfig
  forProvider:
    allowedRedirectUris: 
    - https://vault-127-0-0-1.nip.io/ui/vault/auth/oidc/oidc/callback
    - http://localhost:8250/oidc/callback
    roleName: default
    userClaim: sub
    groupsClaim: groups
    tokenPolicies: 
    - default
    tokenNoDefaultPolicy: true
    tokenType: service
    verboseOidcLogging: true
    oidcScopes:
    - groups
    roleType: oidc
    backend: oidc
   # policies: default #needed?
