site_name: kubriX
site_description: 'User documentation for kubriX Showcase'
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Overview: index.md
  - Tools: tools.md
  - Onboarding teams and apps:
      - Onboarding teams: onboarding/onboarding-teams.md
      - Onboarding apps: onboarding/onboarding-apps.md
      - Promoting changes with kargo: onboarding/promoting-changes.md
      - Additional infos: onboarding/additional-infos.md
  - Observability:
      - Overview: observability/overview.md
      - Alerting: observability/alerting.md
  - CloudNativePG: cloudnativepg.md
  - GRC:
      - Backup and Recovery: grc/backuprecovery.md
      - Identity and Access Management: grc/iam.md
      - RBAC Portal: grc/rbacportal.md
      - Backstage Authorization and Integration: grc/backstage_auth.md
      - Centralized RBAC with OIDC: grc/rbac-oidc.md
  - Application Migration:
      - Migration Process Steps: application-migration/migration-process.md
      - Learning Path for Developers: application-migration/learning-path.md
  - Platform-Admin Documentation:
      - Adding and maintaining building blocks: platform-building-blocks.md
      - Testing the platform: platform-testing.md
      - Mimir Runbooks: runbooks/mimir.md
      - Loki Runbooks: runbooks/loki.md
  - Hub & Spoke (kubriX prime):
      - Hub & Spoke Architecture: hub-and-spoke/hub-and-spoke-basics.md
      - Deploying custom apps to spokes: hub-and-spoke/application-deployment.md
