site_name: kubriX
site_description: 'User documentation for kubriX Showcase'
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Overview: index.md
  - Tools: tools.md
  - Application Migration:
      - Migration Process Steps: application-migration/migration-process.md
      - Learning Path for Developers: application-migration/learning-path.md
  - Platform-Admin Documentation:
      - Adding and maintaining building blocks: platform-building-blocks.md
      - Testing the platform: platform-testing.md