site_name: kubriX
site_description: 'User documentation for kubriX Showcase'
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Overview: index.md
  - Onboarding teams and apps: ONBOARDING.md
  - Observability: observability.md
  - CloudNativePG: cloudnativepg.md
  - GRC:
      - Backup and Recovery: grc/backuprecovery.md
      - Identity and Access Management: grc/iam.md
      - RBAC Portal: grc/rbacportal.md
  - Application Migration:
      - Migration Process Steps: application-migration/migration-process.md
      - Learning Path for Developers: application-migration/learning-path.md
  - Platform-Admin Documentation:
      - Adding and maintaining building blocks: platform-building-blocks.md
      - Testing the platform: platform-testing.md
      - Mimir Runbooks: runbooks/mimir.md
      - Loki Runbooks: runbooks/loki.md
