site_name: sx-cnp-oss
site_description: 'User documentation for sX cnp oss Showcase'
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Overview: index.md
  - Onboarding teams and apps: ONBOARDING.md
  - Observability: observability.md
  - Application Migration:
      - Migration Process Steps: application-migration/migration-process.md
      - Learning Path for Developers: application-migration/learning-path.md
  - Platform-Admin Documentation:
      - Adding and maintaining building blocks: platform-building-blocks.md
      - Testing the platform: platform-testing.md
