apiVersion: v1
kind: Secret
metadata:
  name: sx-cnp-secret
  labels: 
    app: sx-cnp-secret
type: Opaque
data:
  VAULT_TOKEN: dGJkCg==
  VAULT_ADDR: dGJkCg==
  RH_IMAGE_REGISTRY_TOKEN: dGJkCg==
  RH_IMAGE_REGISTRY_URL: YXBpLmNsdXN0ZXIxLm1jcC5waXRhZ29yYS5hdDo2NDQzCg==
  JIRA_TOKEN: dGJkCg==
  JIRA_URL: aHR0cHM6Ly9zdXhlc3MtaXQuYXRsYXNzaWFuLm5ldAo=
  BACKEND_SECRET: N2d2UWQ0SC9RVjRxMHpZVDduY1owVmMweTNuY0lIVVE=
