apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sx-oidc-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sx-oidc-secret
    template:
      type: Opaque
      data:
        OIDC_CLIENTSECRET: "{{ `{{ .OIDC_CLIENTSECRET }}` }}"
      metadata:
        annotations:
          kubrix.io/install: "false"
  data:
  - secretKey: OIDC_CLIENTSECRET
    remoteRef:
      key: kubrix-kv/data/keycloak/oidc
      property: backstage
