teams:
# new team stanza for team ${{ steps['catalogFetch'].output.entity.metadata.name }}
  - name:  ${{ steps['catalogFetch'].output.entity.metadata.name }}
    sourceRepos:
      - 'https://github.com/${{ parameters.teamOrg }}/${{`{{ steps['catalogFetch'].output.entity.metadata.name }}`}}-*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/${{ parameters.teamOrg }}/${{ steps['catalogFetch'].output.entity.metadata.name }}-apps
      path: .
      revision: main
    multiStageKargoAppSet:
      github:
        organization: ${{ parameters.teamOrg }}
