teams:
# new team stanza for team kubrix
  - name:  kubrix
    sourceRepos:
      - '*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/kubrixBot/kubrix-apps
      path: .
      revision: main
    multiStageKargoAppSet:
      github:
        organization: kubrixBot
