teams:
  - name: team1
    sourceRepos:
      - '*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      # also allow kargo Project cluster resource,
      # all details why is documented currently in
      # https://github.com/akuity/kargo/issues/2058
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/suxess-it/team1-apps
      path: k3d-apps
      revision: main
    multiStageKargoAppSet:
      organization: suxess-it
  - name: team2
    sourceRepos:
      - '*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/suxess-it/team2-apps
      path: k3d-apps
      revision: main
    # in the future maybe also some attributes for an scm / git application-set instead of appOfApps possible
    scmAppSet: ~
    gitAppSet: ~
