teams:
# new team stanza for team kubrix
  - name: kubrix
    sourceRepos:
      - 'https://github.com/kubriX-demo/kubrix-a2164-*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/kubriX-demo/kubrix-a2164-apps
      path: .
      revision: main
    multiStageKargoAppSet:
      github:
        organization: kubriX-demo
