teams:
# new team stanza for team kubrix
  - name: kubrix
    sourceRepos:
      - 'https://github.com/kubriX-demo/kubrix-a-*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/kubriX-demo/kubrix-a-apps
      path: .
      revision: main
    multiStageKargoAppSet:
      github:
        organization: kubriX-demo
    ## prime-only
    #admins:
    #  - adminuser
    #editors:
    #  - editoruser
    #viewers:
    #  - vieweruser
    ## end prime-only
