{{- if .Values.global.providerUrl }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-cloud-credential
  namespace: velero
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: velero-cloud-credential
    template:
      data:
        cloud: |-
          [default]
          aws_access_key_id: "{{ `{{ .aws_access_key_id }}` }}"
          aws_secret_access_key: "{{ `{{ .aws_secret_access_key }}` }}"
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: {{ .Values.global.secretStore }}/data/demo/minio
      property: username
  - secretKey: aws_secret_access_key
    remoteRef:
      key: {{ .Values.global.secretStore }}/data/demo/minio
      property: password
{{ end }}
