gardenercert:
  enabled: true
  dnsnames: falco.lab.suxessit.k8s.cloud.uibk.ac.at

falco:
  scc:
    create: false

  tty: true

  driver:
    enabled: true
    #kind: ebpf
    kind: modern-bpf
    kubernetes:
      enabled: true

  falco:
    grpc:
      enabled: true
      bind_address: "unix:///run/falco/falco.sock"
    # when threadiness is 0, Falco automatically guesses it depending on the number of online cores
      threadiness: 0

    grpc_output:
      enabled: true

  falcosidekick:
    enabled: true
    webui:
      enabled: true
      replicaCount: 1
      ingress:
        enabled: true
        annotations:
          cert.gardener.cloud/purpose: managed
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/dnsnames: falco.lab.suxessit.k8s.cloud.uibk.ac.at
          dns.gardener.cloud/ttl: "180"          
        ingressClassName: nginx
        hosts:
          - host: falco.lab.suxessit.k8s.cloud.uibk.ac.at
            paths:
              - path: /
                pathType: Prefix
        tls:
            - secretName: falco-server-tls
              hosts:
                - falco.lab.suxessit.k8s.cloud.uibk.ac.at
    replicaCount: 1
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
    prometheusRules:
      enabled: true
    config:
      loki:
        hostport: "http://sx-loki.monitoring.svc.cluster.local:3100"

falco-exporter:
  falco:
    grpcUnixSocketPath: "unix:///run/falco/falco.sock"
    grpcTimeout: 3m

  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
  grafanaDashboard:
    enabled: true
    namespace: monitoring

  prometheusRules:
    enabled: true

k8s-metacollector:
  serviceMonitor:
    create: true
    labels:
      release: "kube-prometheus-stack"
  grafana:
    dashboards:
      enabled: true
      configMaps:
        collector:
          name: k8s-metacollector-grafana-dashboard
          namespace: "monitoring"
