apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
data:
  kubrix.realm.json: |-
{{ .Files.Get "realmsettings/kubrix.realm.json" | indent 4}}
  poststart.sh:  |-
    #!/bin/bash
    #
    # Bootstrap Backstage Client 
    #
    ###### MAIN ######################
    # create crossplane client with admin role -- currently not possible with crossplane only ... 

    sleepSeconds="${1:-60}"
    echo "going to wait for initialization/stabilization of server, sleeping for $sleepSeconds"
    sleep $sleepSeconds

    cd /opt/keycloak/bin

    # login
    ./kcadm.sh config credentials --realm master --user admin --password admin --server http://0.0.0.0:8080
    ./kcadm.sh create clients -r master -s serviceAccountsEnabled=true -s clientId=crossplane -s enabled=true -s secret=demosecret
    ./kcadm.sh add-roles --uusername service-account-crossplane --rolename admin -r master
    ./kcadm.sh update events/config -r master -s enabledEventTypes=[]
    ./kcadm.sh update events/config -r master -s adminEventsEnabled=true -s adminEventsDetailsEnabled=true

    exit 0
