---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  labels:
    type: provider-credentials
type: Opaque
stringData:
    # credentials username MUST be the same as adminUser from values file
    # credentials password MUST be the same as adminPassword
  credentials: |
    {
      "admin-password": "admin1",
      "username": "admin",
      "password": "admin1",
      "url": "http://{{ .Release.Name }}-headless.{{ .Release.Namespace }}.svc.cluster.local:8080",
      "client_id": "admin-cli",
      "realm": "master",
      "tls_insecure_skip_verify": "true"
    }