apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: keycloak-mrap
spec:
  activate:
  - authbackends.jwt.vault.upbound.io
  - realms.realm.keycloak.crossplane.io
  - authbackendroles.jwt.vault.upbound.io
  - protocolmappers.client.keycloak.crossplane.io
  - roles.role.keycloak.crossplane.io
  - roles.group.keycloak.crossplane.io
  - groups.group.keycloak.crossplane.io
  - users.user.keycloak.crossplane.io
  - clientscopes.openidclient.keycloak.crossplane.io
  - clientdefaultscopes.openidclient.keycloak.crossplane.io
  - clients.openidclient.keycloak.crossplane.io
  - memberships.group.keycloak.crossplane.io
  
