---
apiVersion: v1
kind: Secret
metadata:
  name: cp-keycloak-user-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  labels:
    type: user-credentials
type: Opaque
stringData:
  # must match users from values file
  phac: "test"
  jokl: "test"
  backstageadmin: "test"
  demouser: "test"
  demouser: "test"
  demoadmin: "test"
  team1user: "test"
