---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-client-{{ .Values.deployments.keycloak.vaultclient.config.clientID }}-password"
type: Opaque
stringData:
  {{ .Values.deployments.keycloak.vaultclient.config.clientID }}: {{ .Values.deployments.keycloak.vaultclient.config.clientSecret }}

---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: {{ .Values.deployments.keycloak.vaultclient.config.clientID }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: CONFIDENTIAL 
    clientId: {{ .Values.deployments.keycloak.vaultclient.config.clientID }}
    name: {{ .Values.deployments.keycloak.vaultclient.config.clientID }}
    realmId: {{ .Values.deployments.keycloak.realm.realmid }}
    directAccessGrantsEnabled: false
    standardFlowEnabled: true
    serviceAccountsEnabled: true
#    managementPolicies: ["Observe"]
    validRedirectUris:
      - "http://localhost:7007/api/auth/oidc/handler/frame"
      - "https://backstage{{ .Values.deployments.ingress.fqdn }}/api/auth/oidc/handler/frame"
    clientSecretSecretRef:
      key: {{ .Values.deployments.keycloak.vaultclient.config.clientID }}
      name: "{{ .Release.Name }}-client-{{ .Values.deployments.keycloak.vault.client.config.clientID }}-password"
      namespace: {{ .Release.Namespace }}
    loginTheme: keycloak
  providerConfigRef:
    name: "{{ .Release.Name }}-config"
