---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-credentials"
type: Opaque
stringData:
  keycloak-credentials: |
    {
      "username":{{ .Values.secrets.keycloak.admin.name | quote }},
      "client_id": "admin-cli",
      "password":{{ .Values.secrets.keycloak.admin.password | quote }},
      "url": "http://{{ .Values.deployments.keycloak.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:8080",
      "realm": "master",
      "tls_insecure_skip_verify": "true"
    }
