---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: CONFIDENTIAL 
    clientId: backstage
    name: backstage
    realmId: {{ .Values.kubrix.keycloak.realm.realmid }}
    directAccessGrantsEnabled: false
    standardFlowEnabled: true
    serviceAccountsEnabled: true
#    managementPolicies: ["Observe"]
    validRedirectUris:
      - "http://localhost:7007/api/auth/oidc/handler/frame"
      - "https://backstage{{ .Values.kubrix.keycloak.domainName }}/api/auth/oidc/handler/frame"
    clientSecretSecretRef:
      key: backstage
      name: keycloak-client-credentials
      namespace: {{ .Release.Namespace }}
    loginTheme: keycloak.v2
  providerConfigRef:
    name: "{{ .Release.Name }}-config"
