---
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: {{ .Values.kubrix.keycloak.realm.realmid }}
  labels:
    platform-engineer.cloud/realm: {{ .Values.kubrix.keycloak.realm.realmid }}
  annotations:
    link.argocd.argoproj.io/external-link: https://keycloak{{ .Values.kubrix.keycloak.fqdn }}/admin/master/console/#/{{ .Values.kubrix.keycloak.realm.realmid }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    realm: {{ .Values.kubrix.keycloak.realm.realmid }}
    displayName: {{ .Values.kubrix.keycloak.realm.realmid }}
    attributes:
      frontendUrl: https://keycloak{{ .Values.kubrix.keycloak.fqdn }}
  deletionPolicy: "Delete"
  providerConfigRef:
    name: "{{ .Release.Name }}-config"
