---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: CONFIDENTIAL 
    clientId: openbao
    name: openbao
    realmId: {{ .Values.kubrix.keycloak.realm.realmid }}
    adminUrl: "https://openbao{{ .Values.kubrix.keycloak.domainName }}"
    rootUrl: "https://openbao{{ .Values.kubrix.keycloak.domainName }}"
    directAccessGrantsEnabled: false
    standardFlowEnabled: true
    serviceAccountsEnabled: true
#    managementPolicies: ["Observe"]
    validRedirectUris:
      - "https://openbao{{ .Values.kubrix.keycloak.domainName }}/ui/vault/auth/oidc/oidc/callback"
    clientSecretSecretRef:
      key: openbao
      name: keycloak-client-credentials
      namespace: {{ .Release.Namespace }}
    loginTheme: keycloak.v2
  providerConfigRef:
    name: "{{ .Release.Name }}-config"