apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.deployments.keycloak.service.name }}"
  annotations:
{{- if .Values.gardenercert.enabled }}
    cert.gardener.cloud/purpose: managed
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: {{ .Values.deployments.ingress.host }}
    dns.gardener.cloud/ttl: "180"
{{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  tls:
    - hosts:
        - "{{ .Values.deployments.ingress.host }}"
      secretName: "{{ .Values.secrets.tls.name }}"
  rules:
    - host: "{{ .Values.deployments.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.deployments.keycloak.service.name }}"
                port:
                  number: {{.Values.deployments.keycloak.ports.containerPort}}
