apiVersion: keycloak.crossplane.io/v1alpha1
kind: XBuiltinObjects
metadata:
  name: keycloak-builtin-objects-{{ .Values.kubrix.keycloak.realm.realmid }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigName: sx-keycloak-config
  providerSecretName: keycloak-credentials-xr
  realm: {{ .Values.kubrix.keycloak.realm.realmid }}
  builtinClients: 
    - account
    - account-console
    - admin-cli
    - broker
    - realm-management
    - security-admin-console
  builtinRealmRoles:
    - offline_access
    - uma_authorization
  builtinAuthenticationFlows: []
