backupStorageLocation:
  config:
    s3Url: https://sx-minio.minio.svc.cluster.local:9000
    bucket: velero
    region: minio
    insecureSkipTLSVerify: true # temp for minio/local deployment
velero:
  configuration:
    defaultVolumesToFsBackup: false #use CSI snapshots in metalstack environments
  snapshotsEnabled: true #snapshots are supported in metalstack environments
