cloudnative-pg:
  replicaCount: 2
  monitoring:
    podMonitorEnabled: true
  commonAnnotations:
    argocd.argoproj.io/sync-wave: "-2"
## pgadmin for demopurposes
pgadmin4:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert.gardener.cloud/purpose: managed
      dns.gardener.cloud/class: garden
      dns.gardener.cloud/dnsnames: pgadmin.lab.suxessit.k8s.cloud.uibk.ac.at
      dns.gardener.cloud/ttl: "180"   
    hosts:
      - host: pgadmin.lab.suxessit.k8s.cloud.uibk.ac.at
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: pgadmin-server-tls
        hosts:
          - pgadmin.lab.suxessit.k8s.cloud.uibk.ac.at
  extraConfigmapMounts:
    - name: configmap
      configMap: pgadminconfiglocal
      mountPath: /pgadmin4/config_local.py
      subPath: config_local.py
      readOnly: true
  envVarsFromSecrets:
    - pgadmin-secret
  serverDefinitions:
    enabled: true
    servers:
      backstagePG:
        Name: "backstagePG"
        Group: "kubriX"
        Port: 5432
        Username: backstage
        Host: sx-backstage-cluster-rw.backstage.svc.cluster.local
        MaintenanceDB: "postgres"
  existingSecret: pgadmin-secret
  env:
    email: admin@kubrix.io