{{- if .Values.eso.providerUrl }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-cloud-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-admin-secret
    template:
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.eso.secretStore }}/data/demo/loginuser
      property: username
  - secretKey: password
    remoteRef:
      key: {{ .Values.eso.secretStore }}/data/demo/loginuser
      property: password
{{ end }}