{{- if eq (default false .Values.pgadmin4.enabled) true }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: cnpg
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
    template:
      type: kubernetes.io/basic-auth
      data:
        password: "{{ `{{ .pgadminsecret }}` }}"
        pgadminclientid: "{{ `{{ .pgadminclientid }}` }}"
        pgadminclientsecret: "{{ `{{ .pgadminclientsecret }}` }}"
  data:
  - secretKey: pgadminsecret
    remoteRef:
      key: kubrix-kv/data/cnpg/base
      property: pgadminsecret
  - secretKey: pgadminclientid
    remoteRef:
      key: kubrix-kv/data/cnpg/base
      property: pgadminclientid
  - secretKey: pgadminclientsecret
    remoteRef:
      key: kubrix-kv/data/cnpg/base
      property: pgadminclientsecret
{{- end }}