{{- range .Values.teams }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}-project
spec:
  sourceNamespaces:
  - adn-{{ .name }}
  clusterResourceWhitelist:
{{ toYaml .clusterResourceWhitelist | indent 2 }}
  destinations:
  - name: in-cluster
    namespace: {{ .name }}-*
    server: https://kubernetes.default.svc
  - name: in-cluster
    namespace: adn-{{ .name }}
    server: https://kubernetes.default.svc
  sourceRepos:
{{- range .sourceRepos }}
  - {{ quote . }}
{{- end }}
---
{{- end }}
