
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/trivy-scan-diff.yaml'
      - '.github/create-trivy-scan-diff.sh'
      - 'platform-apps/charts/**'
      
permissions:
  contents: read
  pull-requests: write

name: trivy scan diff

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v5
        with:
         path: pr
         fetch-depth: 0
      - name: Checkout Target of PR
        uses: actions/checkout@v5
        with:
          path: target
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: create trivy scan diff
        id: scan-diff
        shell: bash
        run: |
          bash pr/.github/create-trivy-scan-diff.sh

      - name: PR comment default values with file
        if: env.CHANGES == 'true'
        uses: thollander/actions-comment-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file-path: out/comment-diff-trivy-scan-result.txt